
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Client extends javax.swing.JFrame {
    static Socket mysocket;
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        top_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        center_panel = new javax.swing.JPanel();
        toy_details_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        code_label = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        toy_description = new javax.swing.JTextField();
        price_label = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        dom_label = new javax.swing.JLabel();
        dom = new javax.swing.JTextField();
        batch_number_label = new javax.swing.JLabel();
        batch_number = new javax.swing.JTextField();
        toy_name = new javax.swing.JTextField();
        name_label1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        street_name_label = new javax.swing.JLabel();
        company_name = new javax.swing.JTextField();
        company_name_label = new javax.swing.JLabel();
        street_name = new javax.swing.JTextField();
        zip_code_label = new javax.swing.JLabel();
        zip_code = new javax.swing.JTextField();
        country_label = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        send_toy_details = new javax.swing.JButton();
        send_toy_details1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        server_messages = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        top_panel.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Planet Toys");

        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_panelLayout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_panelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel1.add(top_panel, java.awt.BorderLayout.PAGE_START);

        center_panel.setLayout(new java.awt.CardLayout());

        toy_details_panel.setBackground(new java.awt.Color(255, 255, 255));
        toy_details_panel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                toy_details_panelComponentAdded(evt);
            }
        });
        toy_details_panel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                toy_details_panelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        toy_details_panel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                toy_details_panelFocusGained(evt);
            }
        });
        toy_details_panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                toy_details_panelComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Toy Details");

        code_label.setForeground(new java.awt.Color(102, 102, 102));
        code_label.setText("Code");

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        name_label.setForeground(new java.awt.Color(102, 102, 102));
        name_label.setText("Name");

        toy_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_descriptionActionPerformed(evt);
            }
        });

        price_label.setForeground(new java.awt.Color(102, 102, 102));
        price_label.setText("Price");

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        dom_label.setForeground(new java.awt.Color(102, 102, 102));
        dom_label.setText("Date of Manufacture");

        dom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domActionPerformed(evt);
            }
        });

        batch_number_label.setForeground(new java.awt.Color(102, 102, 102));
        batch_number_label.setText("Batch Number");

        batch_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batch_numberActionPerformed(evt);
            }
        });

        toy_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_nameActionPerformed(evt);
            }
        });

        name_label1.setForeground(new java.awt.Color(102, 102, 102));
        name_label1.setText("Toy Description");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(code)
                            .addComponent(code_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toy_description)
                            .addComponent(price_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(price)
                            .addComponent(dom_label, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(dom)
                            .addComponent(batch_number_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(batch_number)
                            .addComponent(toy_name)
                            .addComponent(name_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(code_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toy_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(toy_description, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dom_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(batch_number_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batch_number, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manufacturer Details");

        street_name_label.setForeground(new java.awt.Color(102, 102, 102));
        street_name_label.setText("Street Address");

        company_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_nameActionPerformed(evt);
            }
        });

        company_name_label.setForeground(new java.awt.Color(102, 102, 102));
        company_name_label.setText("Company Name");

        street_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                street_nameActionPerformed(evt);
            }
        });

        zip_code_label.setForeground(new java.awt.Color(102, 102, 102));
        zip_code_label.setText("Zip Code");

        zip_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zip_codeActionPerformed(evt);
            }
        });

        country_label.setForeground(new java.awt.Color(102, 102, 102));
        country_label.setText("Country");

        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });

        send_toy_details.setBackground(new java.awt.Color(0, 0, 153));
        send_toy_details.setForeground(new java.awt.Color(255, 255, 255));
        send_toy_details.setText("Send Details");
        send_toy_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_toy_detailsActionPerformed(evt);
            }
        });

        send_toy_details1.setBackground(new java.awt.Color(0, 0, 153));
        send_toy_details1.setForeground(new java.awt.Color(255, 255, 255));
        send_toy_details1.setText("Send Thank You Message");
        send_toy_details1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_toy_details1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(send_toy_details, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(country_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zip_code, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zip_code_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(street_name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(street_name_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(company_name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(company_name_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(country, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(send_toy_details1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                        .addGap(24, 32, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(street_name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(street_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(zip_code_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zip_code, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(country_label, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(send_toy_details, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(send_toy_details1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("© Planet Toys 2020");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane2.setFocusable(false);

        server_messages.setEditable(false);
        server_messages.setColumns(20);
        server_messages.setRows(5);
        server_messages.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                server_messagesComponentShown(evt);
            }
        });
        server_messages.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                server_messagesPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(server_messages);

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Chat History:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout toy_details_panelLayout = new javax.swing.GroupLayout(toy_details_panel);
        toy_details_panel.setLayout(toy_details_panelLayout);
        toy_details_panelLayout.setHorizontalGroup(
            toy_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toy_details_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toy_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toy_details_panelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toy_details_panelLayout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(toy_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(toy_details_panelLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        toy_details_panelLayout.setVerticalGroup(
            toy_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toy_details_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(toy_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        center_panel.add(toy_details_panel, "card2");

        jPanel1.add(center_panel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed

    }//GEN-LAST:event_codeActionPerformed

    private void toy_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toy_descriptionActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void domActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domActionPerformed

    private void batch_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batch_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batch_numberActionPerformed

    private void company_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company_nameActionPerformed

    private void street_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_street_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_street_nameActionPerformed

    private void zip_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zip_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zip_codeActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    public static Socket getMysocket() {
        return mysocket;
    }

    public static void setMysocket(Socket mysocket) {
        Client.mysocket = mysocket;
    }


    private void send_toy_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_toy_detailsActionPerformed
            String toy_code = code.getText().trim();
            String name_of_toy = toy_name.getText().trim();
            String description_of_toy = toy_description.getText().trim();
            String price_of_toy = price.getText().trim();
            String date = dom.getText().trim();
            String batchNumber = batch_number.getText().trim();
            String companyName = company_name.getText().trim();
            String streetName = street_name.getText().trim();
            String zipCode = zip_code.getText().trim();
            String Country = country.getText().trim();
            
            if(!toy_code.equals("") && !name_of_toy.equals("") && description_of_toy.equals("")
                    && price_of_toy.equals("") && date.equals("") && batchNumber.equals("") 
                    && companyName.equals("")  && streetName.equals("")  && zipCode.equals("")  && Country.equals("")){  
                JSONObject obj=new JSONObject();
                obj.put("Code", code.getText());
                obj.put("Name", toy_name.getText());
                String sent_msg = "Toy Identification Details: " + obj.toJSONString();
                SocketClient s = new SocketClient(Client.getMysocket(),sent_msg);
                server_messages.setText(server_messages.getText().trim() + "\n" + s.msgout);
                code.setText("");
                toy_name.setText("");
                toy_description.setText("");
                price.setText("");
                dom.setText("");
                batch_number.setText("");
                company_name.setText("");
                street_name.setText("");
                zip_code.setText("");
                country.setText("");
               } 
            else if(!toy_code.equals("") && !name_of_toy.equals("") && !description_of_toy.equals("")
                    && !price_of_toy.equals("") && !date.equals("") && !batchNumber.equals("") 
                    && !companyName.equals("")  && !streetName.equals("")  && !zipCode.equals("")  && !Country.equals("")){  
               JSONObject obj=new JSONObject();
                obj.put("Code", code.getText());
                obj.put("Name", toy_name.getText());
                obj.put("Toy Description", toy_description.getText());
                obj.put("Price", price.getText());
                obj.put("Date of Manufacture" , dom.getText());
                obj.put("Batch number", batch_number.getText());
                obj.put("Company", company_name.getText());
                obj.put("Street Address", street_name.getText());
                obj.put("Zip code", zip_code.getText());
                obj.put("Country", country.getText());
                String sent_msg = "All Toy Information: " + obj.toJSONString();
                SocketClient s = new SocketClient(Client.getMysocket(),sent_msg);
                server_messages.setText(server_messages.getText().trim() + "\n" + s.msgout);
                code.setText("");
                toy_name.setText("");
                toy_description.setText("");
                price.setText("");
                dom.setText("");
                batch_number.setText("");
                company_name.setText("");
                street_name.setText("");
                zip_code.setText("");
                country.setText("");
                }
            else if(toy_code.equals("") && !name_of_toy.equals("") && !description_of_toy.equals("")
                    && !price_of_toy.equals("") && !date.equals("") && !batchNumber.equals("") 
                    && companyName.equals("")  && streetName.equals("")  && zipCode.equals("")  && Country.equals("")){ 
                JSONObject obj=new JSONObject();
                obj.put("Name", toy_name.getText());
                obj.put("Toy Description", toy_description.getText());
                obj.put("Price", price.getText());
                obj.put("Date of Manufacture" , dom.getText());
                obj.put("Batch number", batch_number.getText());
                String sent_msg = "Toy Information: " + obj.toJSONString();
                SocketClient s = new SocketClient(Client.getMysocket(),sent_msg);
                server_messages.setText(server_messages.getText().trim() + "\n" + s.msgout);
                code.setText("");
                toy_name.setText("");
                toy_description.setText("");
                price.setText("");
                dom.setText("");
                batch_number.setText("");
                company_name.setText("");
                street_name.setText("");
                zip_code.setText("");
                country.setText("");
            }
           else if(toy_code.equals("") && name_of_toy.equals("") && description_of_toy.equals("")
                    && price_of_toy.equals("") && date.equals("") && batchNumber.equals("") 
                    && !companyName.equals("")  && !streetName.equals("")  && !zipCode.equals("")  && !Country.equals("")){  
               JSONObject obj=new JSONObject();
                obj.put("Company", company_name.getText());
                obj.put("Street Address", street_name.getText());
                obj.put("Zip code", zip_code.getText());
                obj.put("Country", country.getText());
                String sent_msg = "Manufacturer Details: " + obj.toJSONString();
                SocketClient s = new SocketClient(Client.getMysocket(),sent_msg);
                server_messages.setText(server_messages.getText().trim() + "\n" + s.msgout);
                code.setText("");
                toy_name.setText("");
                toy_description.setText("");
                price.setText("");
                dom.setText("");
                batch_number.setText("");
                company_name.setText("");
                street_name.setText("");
                zip_code.setText("");
                country.setText("");
                }
            else{
               JOptionPane.showMessageDialog(null, 
                              "Please Send one of these options:\n "
                                      + "1. Toy Identification Details (toy code, toy name). \n"
                                      + "2. Toy Information (name, description, price, date of manufacture, batch number). \n"
                                      + "3. Toy manufacturer details (company name, street address,zip-code, country). \n"
                                      + "4. All above the Toy Information", 
                              "Error", 
                              JOptionPane.WARNING_MESSAGE);             
                }
                                               
    }//GEN-LAST:event_send_toy_detailsActionPerformed

    private void server_messagesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_server_messagesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_server_messagesPropertyChange

    private void toy_details_panelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_toy_details_panelFocusGained
                // TODO add your handling code here:
    }//GEN-LAST:event_toy_details_panelFocusGained

    private void toy_details_panelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_toy_details_panelComponentShown
             // TODO add your handling code here:
    }//GEN-LAST:event_toy_details_panelComponentShown

    private void server_messagesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_server_messagesComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_server_messagesComponentShown

    private void toy_details_panelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_toy_details_panelAncestorAdded

    }//GEN-LAST:event_toy_details_panelAncestorAdded

    private void toy_details_panelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_toy_details_panelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_toy_details_panelComponentAdded

    private void toy_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toy_nameActionPerformed

    private void send_toy_details1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_toy_details1ActionPerformed
         String thank_you_msg = JOptionPane.showInputDialog("Send Server Thank You Message");
         if(!thank_you_msg.equals("")){
             Random rand = new Random();
             int a = rand.nextInt(10000);
             int b = rand.nextInt(10000);
             int c = rand.nextInt(10000);
             String unique_code = Integer.toString(a) + Integer.toString(b) + Integer.toString(c);
             String thank_msg = thank_you_msg + " Code: " + unique_code;
             SocketClient s = new SocketClient(Client.getMysocket(),thank_msg);
             server_messages.setText(server_messages.getText().trim() + "\n" + s.msgout);
         }
        
    }//GEN-LAST:event_send_toy_details1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         new SocketConnect().setVisible(true);
        Socket S;
     
        String msgin = "";
         while(!msgin.equals("Server Exited"))
             {
                    S = Client.getMysocket();
                  if(S==null){
                     System.out.print("");
                     // S = Client.getMysocket();
                     continue;
                  }
                  else{
                      SocketClient sc = new SocketClient(S);
                      server_messages.setText(server_messages.getText().trim() + "\n" + sc.msgin);
                      msgin = sc.msgin;
                     
                  }
                    }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batch_number;
    private javax.swing.JLabel batch_number_label;
    private javax.swing.JPanel center_panel;
    private javax.swing.JTextField code;
    private javax.swing.JLabel code_label;
    private javax.swing.JTextField company_name;
    private javax.swing.JLabel company_name_label;
    private javax.swing.JTextField country;
    private javax.swing.JLabel country_label;
    private javax.swing.JTextField dom;
    private javax.swing.JLabel dom_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_label1;
    private javax.swing.JTextField price;
    private javax.swing.JLabel price_label;
    private javax.swing.JButton send_toy_details;
    private javax.swing.JButton send_toy_details1;
    private static javax.swing.JTextArea server_messages;
    private javax.swing.JTextField street_name;
    private javax.swing.JLabel street_name_label;
    private javax.swing.JPanel top_panel;
    private javax.swing.JTextField toy_description;
    private javax.swing.JPanel toy_details_panel;
    private javax.swing.JTextField toy_name;
    private javax.swing.JTextField zip_code;
    private javax.swing.JLabel zip_code_label;
    // End of variables declaration//GEN-END:variables
}
